### ISSUE TITLE
Cloned Repo Scan that runs gitleaks on a clone of the repository

### ISSUE THREAD

**Issue by Collinbrown95** [PHACDataHub/ruok-service-autochecker#66]
# Description

[Gitleaks](https://github.com/gitleaks/gitleaks) is a tool that scans the commit history of a Git repository for potential sensitive values (e.g. passwords, API Keys, etc.) that should not have been committed.

It would be valuable to have a "Cloned Repo Scanner" check that runs `gitleaks` on the commit history of the cloned repository and saves the results to a JSON file (e.g. using the `--report-format json` command line option).

The scanner could then read the contents of this JSON file and populate a report associated with a `gitLeaksCheck` or something like this.

**Comment by LilaKelland** [comment]
closed with #77
